version: "3.1"

services:
  front:
    container_name: "vue"
    build: ./front
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./front:/usr/app/front
  back:
    container_name: "express"
    build: ./back
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./back/:/usr/app/back
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
